[package]
name = "nymyac"
version = "0.2.0-alpha.3"
edition = "2021"
description = "NymyaLang Compiler"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "nymyac"
path = "src/main.rs"